version: '3.7'

services:
  dev:
    container_name: netops
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      - NODE_ENV=development
