version: '3.7'

services:
  dev:
    container_name: netops
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
    links:
      - mailer
    environment:
      - NODE_ENV=development
  mailer:
    container_name: mailer
    build:
      context: ./mailer
      dockerfile: Dockerfile
    volumes:
      - './mailer:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
